/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XeOToRouteImport } from './routes/xe-o-to'
import { Route as IndexRouteImport } from './routes/index'
import { Route as XeOToModelRouteImport } from './routes/xe-o-to.$model'

const XeOToRoute = XeOToRouteImport.update({
  id: '/xe-o-to',
  path: '/xe-o-to',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const XeOToModelRoute = XeOToModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => XeOToRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/xe-o-to': typeof XeOToRouteWithChildren
  '/xe-o-to/$model': typeof XeOToModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/xe-o-to': typeof XeOToRouteWithChildren
  '/xe-o-to/$model': typeof XeOToModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/xe-o-to': typeof XeOToRouteWithChildren
  '/xe-o-to/$model': typeof XeOToModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/xe-o-to' | '/xe-o-to/$model'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/xe-o-to' | '/xe-o-to/$model'
  id: '__root__' | '/' | '/xe-o-to' | '/xe-o-to/$model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  XeOToRoute: typeof XeOToRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xe-o-to': {
      id: '/xe-o-to'
      path: '/xe-o-to'
      fullPath: '/xe-o-to'
      preLoaderRoute: typeof XeOToRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xe-o-to/$model': {
      id: '/xe-o-to/$model'
      path: '/$model'
      fullPath: '/xe-o-to/$model'
      preLoaderRoute: typeof XeOToModelRouteImport
      parentRoute: typeof XeOToRoute
    }
  }
}

interface XeOToRouteChildren {
  XeOToModelRoute: typeof XeOToModelRoute
}

const XeOToRouteChildren: XeOToRouteChildren = {
  XeOToModelRoute: XeOToModelRoute,
}

const XeOToRouteWithChildren = XeOToRoute._addFileChildren(XeOToRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  XeOToRoute: XeOToRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
